ext {
    extName = 'AllManga'
    extClass = '.AllManga'
    extVersionCode = 52
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

android {
    namespace = "eu.kanade.tachiyomi.animeextension"

    defaultConfig {
        versionName "14.52"
    }

    sourceSets {
        main {
            manifest.srcFile "AndroidManifest.xml"
        }
    }
}
